### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by brishav** [Heewookji/gtm#1] opened 2023-04-04 05:36 UTC
I am getting this issue after I use this plugin in my project. I had setup my google analytics as well in the firebase. Synced the gradle still got the error.

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method push on channel heewook.kr/gtm_android)
E/flutter (15253): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
E/flutter (15253): <asynchronous suspension>
E/flutter (15253): #1      GtmAndroid.push (package:gtm_android/src/gtm_android.dart:36:20)
E/flutter (15253): <asynchronous suspension>

**Comment by Heewookji** [comment] 2023-04-07 03:24
Hi! Sometimes, after adding a plug-in, it may not be reflected right away.
So could you do a `flutter clean` first? 
If it still doesn't work, can you give me the information below so that I can reproduce the issue?

- pubspec.lock(gtm, gtm_platform, gtm_android version)
- flutter version
- android OS

**Comment by Heewookji** [comment] 2023-04-28 03:16
closing the issue because there are no further comments.

**Comment by Heewookji** [comment] 2023-04-28 03:16
Closing because there are no further comments.

**Closed as completed by Heewookji** 2023-04-28 03:16 UTC
